config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  get '/about', to: 'static_pages#about'

  get 'events/futsal', to: 'events#index_futsal', as: "futsal"
  get 'events/cyclism', to: 'events#index_cyclism', as: "cyclism"
  get 'events/running', to: 'events#index_running', as: "running"
  get 'events/basketball', to: 'events#index_basketball', as: "basketball"
  get 'events/football', to: 'events#index_football', as: "football"

  get 'event/:id', to: 'events#show', as: "event"

  post 'event_participants', to: 'event_participants#create', as: "event_participants"
  delete 'event_participants', to: 'event_participants#destroy', as: "event_participant"

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  resources :events
  resources :locations
  resources :event_participants

  resources :conversations do
    resources :messages
  end

  resources :users, param: :username

end

app/views/shared/_banner.html.erb
<!-- On ferme le container (prédéfini dans bootstrap cad la page) car la banière doit être en dehors de ce container pour s'appliquer sur toute la page -->
</div>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Just2Train&nbsp;</h1>
    <h5>Connecting people, sporting together.</h5>
    <div id=speacial-fav class="sport-fav">
      <%= link_to new_location_path, class: "btn btn-primary btn-lg extra" do %><i class="fas fa-map-marker"> Create an event </i><%end%>
    </div>
    <div class="sport-fav-div">
    <h5> or find the events that already exists</h5>
    <div id=speacial-fav class="sport-fav">
      <%= link_to football_path, class: "btn btn-info btn-lg" do %><i class="fas fa-futbol"> Football </i><%end%>
      <%= link_to basketball_path, class: "btn btn-info btn-lg" do %><i class="fas fa-basketball-ball"> Basketball </i><%end%>
      <%= link_to cyclism_path, class: "btn btn-info btn-lg" do %><i class="fas fa-bicycle"> Cyclism </i><%end%>
      <%= link_to running_path, class: "btn btn-info btn-lg" do %><i class="fas fa-shoe-prints"> Running </i><%end%>
      <%= link_to events_path, class: "btn btn-info btn-lg" do %><i class="fas fa-angle-double-right"> All events </i><%end%>
    </div>

  </div>
</div>

app/views/shared/_content.html.erb
<!-- Content -->
  <div class="container">

    <div class="header">
      <h2>The most recent meet ups</h2>
      <p>Browse to find your next training session</p>
    </div>

      <section class="events-list-scroll">
          <div class="scroll-wrapper">
              <div class="scroll-container">
                  <div class="events-container-scroll">
                      <% @events.each do |event| %>
                      <div class="events-grid-scroll preview-image-left text-center">
                        <div class="overlay">
                            <h3 class="text-cards-profil"><%= link_to 'Read More', "/event/"+event.id.to_s, class: "stop-this-style" %></h3>
                        </div>	
                          <div class="events-element-scroll">
                              
                              <div class="events-content-scroll">
                                <div class="spacing-event-disp">
                                    <% if event.activity.activity_name == "Futsal" %>
                                        <%= image_tag 'futsal_event.jpg' %>
                                    <% end %>
                                    <% if event.activity.activity_name == "Basketball" %>
                                        <%= image_tag 'basket_event.jpg' %>
                                    <% end %>
                                    <% if event.activity.activity_name == "Running" %>
                                        <%= image_tag 'run_event.jpg' %>
                                    <% end %>
                                    <% if event.activity.activity_name == "Cyclisme" %>
                                        <%= image_tag 'cycling_event.jpg' %>
                                    <% end %>
                                    <% if event.activity.activity_name == "Football" %>
                                        <%= image_tag 'soccer_event.jpg' %>
                                    <% end %>
                                </div>
                                  <time class="events-period-scroll">
                                      <%= event.date.strftime("%a, %d %b") %> at <%= event.time.strftime("%H:%M") %>
                                  </time>
                                  <div class="events-title-scroll spacing-event-disp-large"><%= event.name.capitalize %></div>
                                  <div class="events-description-scroll">
                                      <p><%= event.location.place_name %> <%= event.location.city %></p>
                                      <p><%= event.activity.activity_name %> - <%= event.nb_participant %> people</p>
                                      <p>Level: <%= event.level %> - Price: <%= number_to_currency(event.price) %></p>
                                  </div>
                                  <div class="events-footer-scroll">
                                  </div>
                              </div>
                          </div>
                      </div>
                      <% end %>
                  </div>
              </div>
          </div>
      </section>
  </div>

app/views/shared/_footer.html.erb
<footer>
<div class="footer-left">
  <ul>

    <li class="footer-item">
      About Just2Train
    </li>

    <li class="footer-item">
      <%= link_to events_path do %>All events<%end%>
    </li>

    <li class="footer-item">
      <%= link_to cyclism_path do %> Cyclism</i><%end%>
    </li>

    <li class="footer-item">
      <%= link_to football_path do %> Football<%end%>
    </li>

    <li class="footer-item">
      <%= link_to running_path do %> Running </i><%end%>
    </li>

    <li class="footer-item">
      <%= link_to basketball_path do %> Basketball<%end%>
    </li>

  </ul>
</div>



<div class="footer-right">
  <ul>
    <li class="footer-item">
      <%= link_to new_user_session_path do %>Sign In<%end%>
    </li>

    <li class="footer-item">
      <%= link_to new_user_registration_path do %>Sign up<%end%>
    </li>

    <li class="footer-item">
      <%= link_to "Create a meet up", new_location_path %>
    </li>


    <li class="icons-footer"><i class="fab fa-twitter-square"> </i> <i class="fab fa-facebook"></i>  <i class="fab fa-github"></i>


    <li class="footer-item">
      Jut2Train Connecting people, sporting together, All rights reserved © 2018
    </li>
  </ul>

  </div>
  </div>
</footer>

app/views/shared/_generic-small-banner.html.erb
<div class="small-banner jumbotron-fluid">
  <div class="container">
    <h2 class="display-4">Title&nbsp;</h2>
    <p class="lead">Connecting people, sporting together.</p>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav id ="navbar" class="navbar navbar-expand-lg navbar-fixed-top">
   <div class="container-fluid">
  <%= link_to image_tag('j2t-logo-white.png'), root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "JUST2TRAIN", root_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">

      <div class="collapse navbar-collapse" id="navbarSupportedContent">


        <!-- Dropdown for Events -->
        <div class="nav-link">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">EVENTS <span class="caret"></span></a>

              <ul class="dropdown-menu">

                <li class="nav-item">
                  <%= link_to football_path do %><i class="fas fa-futbol"> FOOTBALL </i><%end%>
                </li>

                <li class="nav-item">
                    <%= link_to basketball_path do %><i class="fas fa-basketball-ball"> BASKETBALL</i><%end%>
                </li>

                <li class="nav-item">
                  <%= link_to cyclism_path do %><i class="fas fa-bicycle"> CYCLISM </i><%end%>
                </li>

                <li class="nav-item">
                  <%= link_to running_path do %><i class="fas fa-shoe-prints"> RUNNING </i><%end%>
                </li>

                <li class="nav-item">
                  <%= link_to events_path do %><i class="fas fa-angle-double-right"> ALL EVENTS </i><%end%>
                </li>

              </ul>
          </li>
        </ul>
        </div>
<!-- end of Dropdown for events -->


      <% if user_signed_in? %>
        <div class="nav-link">
          <li class="nav-item">
            <%= link_to "CREATE A MEET UP", new_location_path %>
          </li>
        </div>

        <div class="nav-link">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"> <%= current_user.username.upcase %></i><span class="caret"></span></a>
              <ul class="dropdown-menu">

                <li class="nav-item">
                  <%= link_to "PROFILE", user_path(current_user) %>
                </li>

                <li class="nav-item">
                  <%= link_to 'CHAT', conversations_path, method: 'get'%>
                </li>

                <li class="nav-item">
                  <%= link_to "EDIT ACOUNT", edit_user_registration_path %>
                </li>

                <li class="nav-item">
                  <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
          </li>
        </ul>
      </div>
      <% else %>
        <div class="nav-link">
            <li class="nav-item">
              <%= link_to "SIGN IN", new_user_session_path %>
            </li>
        </div>

        <div class="nav-link">
          <li class="nav-item">
              <%= link_to "SIGN UP", new_user_registration_path %>
            </li>
          </div>
      <% end %>



      </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_preview.html.erb
<!-- Preview <images></images> -->
<div class="container">
    <div class="preview-grid">
        <div class="header">
            <h2>Connect with people, sport together !</h2>
            <p>Just2Train helps you to connect with people around the world. Start now! </p>
        </div>

        <div class="row">
            <div class="column"><!-- Column left -->
                <div class="preview-image-left" id="cyclism">
                    <%= image_tag 'cyclism.jpg' %>
                    <div class="overlay">
                        <%= link_to cyclism_path, class:"text-cards" do %><i class="fas fa-bicycle"> CYCLISM </i><%end%>
                    </div>
                </div>
                <div class="preview-image-left" id="foot">
                    <%= image_tag 'foot.jpg' %>
                    <div class="overlay">
                        <%= link_to football_path, class:"text-cards" do %><i class="fas fa-futbol"> FOOTBALL </i><%end%>
                    </div>
                </div>
                <div class="preview-image-left">
                    <%= image_tag 'running.jpg' %>
                    <div class="overlay">
                      <%= link_to running_path, class:"text-cards" do %><i class="fas fa-shoe-prints"> RUNNING </i><%end%>
                    </div>
                </div>
            </div>

            <div class="column"><!-- Column right -->

                <div class="preview-image-right">
                    <%= image_tag 'basket.jpg' %>
                    <div class="overlay">
                        <%= link_to basketball_path, class:"text-cards" do %><i class="fas fa-basketball-ball"> BASKETBALL</i><%end%>
                    </div>
                </div>

                <div class="preview-image-right">
                    <%= image_tag 'swiming.png' %>
                    <div class="overlay">
                        <%= link_to events_path, class:"text-cards" do %><i class="fas fa-angle-double-right"> AND MANY OTHERS</i><%end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>