config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  get '/about', to: 'static_pages#about'

  get 'events/futsal', to: 'events#index_futsal', as: "futsal"
  get 'events/cyclism', to: 'events#index_cyclism', as: "cyclism"
  get 'events/running', to: 'events#index_running', as: "running"
  get 'events/basketball', to: 'events#index_basketball', as: "basketball"
  get 'events/football', to: 'events#index_football', as: "football"

  get 'event/:id', to: 'events#show', as: "event"

  post 'event_participants', to: 'event_participants#create', as: "event_participants"
  delete 'event_participants', to: 'event_participants#destroy', as: "event_participant"

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  resources :events
  resources :locations
  resources :event_participants

  resources :conversations do
    resources :messages
  end

  resources :users, param: :username

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location
  belongs_to :activity
  has_many :event_participants, dependent: :destroy
  has_many :users, through: :event_participants

  # When testing the presence of foreign key it is necessary to use :model
  validates :name, :date, :time, :location, :activity, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def new
    @event = Event.new
  end

  def index
    @events = Event.all
  end

  def index_futsal
    @events = Event.all
  end

  def index_cyclism
    @events = Event.all
  end

  def index_running
    @events = Event.all
  end

  def index_basketball
    @events = Event.all
  end

  def index_football
    @events = Event.all 
  end

  def show
    @event = Event.find(params[:id])
    @users = User.all
    @conversations = Conversation.all
  end

  private
    def event_params
      params.require(:event).permit(:name, :price, :date, :nb_participant, :level, :time, :activity_id, :location_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<!-- Main wrapper -->
<div class="wrapper">
<!-- Navbar -->
<%= render 'shared/navbar' %>
  <!-- Body container -->
  <body>
    <!-- Small generic banner -->
    <div class="small-banner jumbotron-fluid">
      <div class="container">
        <h2 class="display-4">Events&nbsp;</h2>
        <p class="lead">Find your training session</p>
      </div>
    </div>
    <!-- End of small generic banner -->
    <div class="container">
        <div class="row">

            <div class="events-container">
                <% @events.each do |event| %>
                    <div class="col-md-4 preview-image-left">
                        <div class="overlay">
                            <h3 class="text-cards-profil"><%= link_to 'Read More', "/event/"+event.id.to_s, class: "stop-this-style" %></h3>
                        </div>
                        <div class="events-element">
                            <div class="thumbnail">
                                <% if event.activity.activity_name == "Futsal" %>
                                    <%= image_tag 'futsal_event.jpg', :class => "img-cards" %>
                                <% end %>
                                <% if event.activity.activity_name == "Basketball" %>
                                    <%= image_tag 'basket_event.jpg', :class => "img-cards" %>
                                <% end %>
                                <% if event.activity.activity_name == "Running" %>
                                    <%= image_tag 'run_event.jpg', :class => "img-cards" %>
                                <% end %>
                                <% if event.activity.activity_name == "Cyclisme" %>
                                    <%= image_tag 'cycling_event.jpg', :class => "img-cards" %>
                                <% end %>
                                <% if event.activity.activity_name == "Football" %>
                                    <%= image_tag 'soccer_event.jpg', :class => "img-cards" %>
                                <% end %>
                            </div>
                            <div class="events-content">
                            <div class="events-title"><h3><%= event.name.capitalize %></h3></div>
                                <time class="events-period">
                                    <%= event.date.strftime("%a, %d %b") %> AT <%= event.time.strftime("%H:%M") %>
                                </time>
                                    <div class="caption">
                                        <p class="label-about-desc-opos"><%= event.location.place_name %> <%= event.location.city %></p>
                                        <p class="label-about-desc-opos"><%= event.activity.activity_name %> - <%= event.nb_participant %> people</p>
                                        <p class="label-about-desc-opos">Level: <%= event.level %> - Price: <%= number_to_currency(event.price) %></p>
                                    </div>
                            </div> <!-- End for event-content -->
                        </div><!-- End for event-element -->
                    </div> <!-- End for col-sm-6 col-md-4 -->
                <% end %>
            </div> <!-- End for event- container -->
        </div>
      </div>
  </body>

  <footer>
    <%= render 'shared/footer' %>
  </footer>

app/views/events/index_basketball.html.erb
<!-- Main wrapper -->
<div class="wrapper">
<!-- Navbar -->
<%= render 'shared/navbar' %>
  <!-- Body container -->
  <body>
    <!-- Small generic banner -->
    <div class="small-banner-basket jumbotron-fluid">
      <div class="container">
        <h2 class="display-4">Basketball&nbsp;</h2>
        <p class="lead">Find your training session</p>
      </div>
    </div>
    <!-- End of small generic banner -->
    <div class="container">
      <div class="row">

        <div class="events-container">
            <% @events.each do |event| %>
                <% if event.activity.activity_name == "Basketball" %>
                    <div class="col-md-4 preview-image-left">
                      <div class="overlay">
                          <h3 class="text-cards-profil"><%= link_to 'Read More', "/event/"+event.id.to_s, class: "stop-this-style" %></h3>
                      </div>	
                        <div class="events-element">
                            <div class="thumbnail">
                              <%= image_tag 'basket_event.jpg', :class => "img-cards" %>
                            </div>
                            <div class="events-content">
                              <div class="events-title"><h3><%= event.name.capitalize %></h3></div>
                                <time class="events-period">
                                    <%= event.date.strftime("%a, %d %b") %> AT <%= event.time.strftime("%H:%M") %>
                                </time>
                                      <div class="caption">
                                        <p class="label-about-desc-opos"><%= event.location.place_name %> <%= event.location.city %></p>
                                        <p class="label-about-desc-opos"><%= event.activity.activity_name %> - <%= event.nb_participant %> people</p>
                                        <p class="label-about-desc-opos">Level: <%= event.level %> - Price: <%= number_to_currency(event.price) %></p>
                                      </div>
                            </div> <!-- End for event-content -->
                        </div><!-- End for event-element -->
                    </div> <!-- End for col-sm-6 col-md-4 -->
                <% end %>
            <% end %>
        </div> <!-- End for event- container -->

    </div> <!-- End for row -->
    </div> <!-- End for container -->

  </body>

  <footer>
    <%= render 'shared/footer' %>
  </footer>

app/views/events/index_cyclism.html.erb
<!-- Main wrapper -->
<div class="wrapper">
<!-- Navbar -->
<%= render 'shared/navbar' %>
  <!-- Body container -->
  <body>
    <!-- Small generic banner -->
    <div class="small-banner-cyclism jumbotron-fluid">
      <div class="container">
        <h2 class="display-4">Cyclism&nbsp;</h2>
        <p class="lead">Find your training session</p>
      </div>
    </div>
    <!-- End of small generic banner -->
    <div class="container">
      <div class="row">

        <div class="events-container">
            <% @events.each do |event| %>
                <% if event.activity.activity_name == "Cyclisme" %>
                    <div class="col-md-4 preview-image-left">
                      <div class="overlay">
                          <h3 class="text-cards-profil"><%= link_to 'Read More', "/event/"+event.id.to_s, class: "stop-this-style" %></h3>
                      </div>	
                        <div class="events-element">
                            <div class="thumbnail">
                              <%= image_tag 'cycling_event.jpg', :class => "img-cards" %>
                            </div>
                            <div class="events-content">
                              <div class="events-title"><h3><%= event.name.capitalize %></h3></div>
                                <time class="events-period">
                                    <%= event.date.strftime("%a, %d %b") %> AT <%= event.time.strftime("%H:%M") %>
                                </time>
                                      <div class="caption">
                                        <p class="label-about-desc-opos"><%= event.location.place_name %> <%= event.location.city %></p>
                                        <p class="label-about-desc-opos"><%= event.activity.activity_name %> - <%= event.nb_participant %> people</p>
                                        <p class="label-about-desc-opos">Level: <%= event.level %> - Price: <%= number_to_currency(event.price) %></p>
                                      </div>
                            </div> <!-- End for event-content -->
                        </div><!-- End for event-element -->
                    </div> <!-- End for col-sm-6 col-md-4 -->
                <% end %>
            <% end %>
        </div> <!-- End for event- container -->

    </div> <!-- End for row -->
    </div> <!-- End for container -->

  </body>

  <footer>
    <%= render 'shared/footer' %>
  </footer>

app/views/events/index_football.html.erb
<!-- Main wrapper -->
<div class="wrapper">
<!-- Navbar -->
<%= render 'shared/navbar' %>
  <!-- Body container -->
  <body>
    <!-- Small generic banner -->
    <div class="small-banner-football jumbotron-fluid">
      <div class="container">
        <h2 class="display-4">Football&nbsp;</h2>
        <p class="lead">Find your training session</p>
      </div>
    </div>
    <!-- End of small generic banner -->
    <div class="container">
      <div class="row">

        <div class="events-container">
            <% @events.each do |event| %>
                <% if event.activity.activity_name == "Football" %>
                    <div class="col-md-4 preview-image-left">
                      <div class="overlay">
                          <h3 class="text-cards-profil"><%= link_to 'Read More', "/event/"+event.id.to_s, class: "stop-this-style" %></h3>
                      </div>	
                        <div class="events-element">
                            <div class="thumbnail">
                              <%= image_tag 'soccer_event.jpg', :class => "img-cards" %>
                            </div>
                            <div class="events-content">
                              <div class="events-title"><h3><%= event.name.capitalize %></h3></div>
                                <time class="events-period">
                                    <%= event.date.strftime("%a, %d %b") %> AT <%= event.time.strftime("%H:%M") %>
                                </time>
                                      <div class="caption">
                                        <p class="label-about-desc-opos"><%= event.location.place_name %> <%= event.location.city %></p>
                                        <p class="label-about-desc-opos"><%= event.activity.activity_name %> - <%= event.nb_participant %> people</p>
                                        <p class="label-about-desc-opos">Level: <%= event.level %> - Price: <%= number_to_currency(event.price) %></p>
                                      </div>
                            </div> <!-- End for event-content -->
                        </div><!-- End for event-element -->
                    </div> <!-- End for col-sm-6 col-md-4 -->
                <% end %>
            <% end %>
        </div> <!-- End for event- container -->

    </div> <!-- End for row -->
    </div> <!-- End for container -->

  </body>

  <footer>
    <%= render 'shared/footer' %>
  </footer>

app/views/events/index_futsal.html.erb
<!-- Main wrapper -->
<div class="wrapper">
<!-- Navbar -->
<%= render 'shared/navbar' %>
  <!-- Body container -->
  <body>
    <!-- Small generic banner -->
    <div class="small-banner jumbotron-fluid">
      <div class="container">
        <h2 class="display-4">Futsal&nbsp;</h2>
        <p class="lead">Find your training session</p>
      </div>
    </div>
    <!-- End of small generic banner -->
    <div class="container">
      <div class="row">

        <div class="events-container">
            <% @events.each do |event| %>
                <% if event.activity.activity_name == "Futsal" %>
                    <div class="col-md-4 preview-image-left">
                      <div class="overlay">
                          <h3 class="text-cards-profil"><%= link_to 'Read More', "/event/"+event.id.to_s, class: "stop-this-style" %></h3>
                      </div>	
                        <div class="events-element">
                            <div class="thumbnail">
                              <%= image_tag 'futsal_event.jpg', :class => "img-cards" %>
                            </div>
                            <div class="events-content">
                              <div class="events-title"><h3><%= event.name.capitalize %></h3></div>
                                <time class="events-period">
                                    <%= event.date.strftime("%a, %d %b") %> AT <%= event.time.strftime("%H:%M") %>
                                </time>
                                      <div class="caption">
                                        <p class="label-about-desc-opos"><%= event.location.place_name %> <%= event.location.city %></p>
                                        <p class="label-about-desc-opos"><%= event.activity.activity_name %> - <%= event.nb_participant %> people</p>
                                        <p class="label-about-desc-opos">Level: <%= event.level %> - Price: <%= number_to_currency(event.price) %></p>
                                      </div>
                            </div> <!-- End for event-content -->
                        </div><!-- End for event-element -->
                    </div> <!-- End for col-sm-6 col-md-4 -->
                <% end %>
            <% end %>
        </div> <!-- End for event- container -->

    </div> <!-- End for row -->
    </div> <!-- End for container -->

  </body>

  <footer>
    <%= render 'shared/footer' %>
  </footer>

app/views/events/index_running.html.erb
<!-- Main wrapper -->
<div class="wrapper">
<!-- Navbar -->
<%= render 'shared/navbar' %>
  <!-- Body container -->
  <body>
    <!-- Small generic banner -->
    <div class="small-banner-running jumbotron-fluid">
      <div class="container">
        <h2 class="display-4">Running&nbsp;</h2>
        <p class="lead">Find your training session</p>
      </div>
    </div>
    <!-- End of small generic banner -->
    <div class="container">
      <div class="row">

        <div class="events-container">
            <% @events.each do |event| %>
                <% if event.activity.activity_name == "Running" %>
                    <div class="col-md-4 preview-image-left">
                      <div class="overlay">
                          <h3 class="text-cards-profil"><%= link_to 'Read More', "/event/"+event.id.to_s, class: "stop-this-style" %></h3>
                      </div>	
                        <div class="events-element">
                            <div class="thumbnail">
                              <%= image_tag 'run_event.jpg', :class => "img-cards" %>
                            </div>
                            <div class="events-content">
                              <div class="events-title"><h3><%= event.name.capitalize %></h3></div>
                                <time class="events-period">
                                    <%= event.date.strftime("%a, %d %b") %> AT <%= event.time.strftime("%H:%M") %>
                                </time>
                                      <div class="caption">
                                        <p class="label-about-desc-opos"><%= event.location.place_name %> <%= event.location.city %></p>
                                        <p class="label-about-desc-opos"><%= event.activity.activity_name %> - <%= event.nb_participant %> people</p>
                                        <p class="label-about-desc-opos">Level: <%= event.level %> - Price: <%= number_to_currency(event.price) %></p>
                                      </div>
                            </div> <!-- End for event-content -->
                        </div><!-- End for event-element -->
                    </div> <!-- End for col-sm-6 col-md-4 -->
                <% end %>
            <% end %>
        </div> <!-- End for event- container -->

    </div> <!-- End for row -->
    </div> <!-- End for container -->

  </body>

  <footer>
    <%= render 'shared/footer' %>
  </footer>

app/views/events/show.html.erb
<!-- Main wrapper -->
<div class="wrapper">
<!-- Navbar -->
<%= render 'shared/navbar' %>
  <!-- Body container -->
  <body>
    <!-- Small generic banner -->
    <div class="small-banner jumbotron-fluid">
      <div class="container">
        <h2 class="display-4"> All Events&nbsp;</h2>
        <p class="lead">Find your next training session</p>
      </div>
    </div><!-- Body container -->

          <div class="container">
            <div class="event-wrapper">

                <div class="row">

                    <div class="col-md-3">

                        <h4 class="event-detail">
                            <div class="event-activity">
                                Activity :
                            </div>
                            <div class="event-bright-element">
                                <%= @event.activity.activity_name %>
                            </div>
                            <div class="event-bright-element">
                                <%= @event.nb_participant %>
                            </div>
                            <div class="event-participant-number-need">
                                 people needed
                            </div>
                            <br>
                            <div class="event-participant-number-got">
                                Already
                                <div class="event-bright-element">
                                <%= @event.event_participants.size %>
                                </div>
                                participants
                            </div>
                        </h4>

                        <div class="event-date-div">
                            <div class="event-date">
                                <div class="event-day-calendar">
                                    <%= @event.date.strftime("%a") %>
                                </div>
                                <div class="event-at">
                                    AT
                                </div>
                                <div>
                                    <%= @event.time.strftime("%H:%M") %>
                                </div>
                                <div class="mini-date-display">
                                    <span><%= @event.date.strftime("%e %b %Y") %> </span>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="col-md-6">

                            <div class="event-location">
                              <div class="event-title-div">
                                  <h3><%= @event.name.capitalize %></h3>
                              </div>
                                <div class="event-location-name">
                                    <%= @event.location.place_name %></span>
                                </div>
                                <div class="event-location-adress">
                                    <%= @event.location.street1 %> <%= @event.location.street2 %>
                                </div>
                                <div class="event-location-zip">
                                    <%= @event.location.zip %>, <%= @event.location.city %></span>
                                </div>
                            </div>
                            <div id="mapid">
                            <script type="text/javascript">
                                var mymap = L.map('mapid').setView(['48.862725', '2.287592000000018'], 13);
                                L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=<%= ENV['MAPBOX'] %>', {
                                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                                maxZoom: 18,
                                id: 'mapbox.streets',
                            }).addTo(mymap);
                            var marker = L.marker(['48.862725', '2.287592000000018']).addTo(mymap);
                            </script>
                            </div>
                            <div class="button-space-up">
                              <!-- Buttons under map -->
                              <div class="register-button button-events-div">
                                <%= link_to edit_location_path(@event.location), class: "btn btn-success" do %><i class="fas fa-edit"> Modify Event</i><%end%>
                              </div>
                            </div>
                    </div>



                    <div class="col-md-3">
                        <% if is_participant? != true %>
                            <div class="register-button button-events-div">
                                <%= link_to ' Count Me In ', event_participants_path(:event_id => @event.id), class: "btn btn-dark button-events", method: :post %>
                            </div>
                        <% end %>
                        <% if is_participant? == true %>
                          <div class="register-button button-events-div">
                              <%= link_to 'Cancel Participation', event_participant_path(event_id: @event.id), class: "btn btn-dark button-participation-cancel", method: :delete, data: { confirm: "Are you sure?" } %>
                          </div>
                        <% end %>
                            <div class='participant-box'>
                                <h4 class="participant-disp">
                                    Participants :
                                </h4>
                            <% if is_participant? == true %>
                                <div class="event-i-do-div">
                                    <p class="event-i-do-it">ME</p>
                                </div>
                            <% end %>
                            <% @event.event_participants.each do |participant| %>
                                <% if participant.user.id != current_user.id %>
                                    <div class='participant-person'>
                                        <div class="participant-name">
                                            <%= participant.user.username.capitalize %>
                                        </div>
                                        <div >
                                            <%= link_to 'Message', conversations_path(sender_id: current_user.id, recipient_id: participant.id), class: "btn btn-dark participant-msg", method: 'post'%>
                                        </div>
                                    </div>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </body>

</div> <!--End of wrapper -->
<footer>
    <%= render 'shared/footer' %>
</footer>